const ActionTypes = {}

//for Popular Brand
export const POPULAR_BRAND_WATCHER = 'POPULAR_BRAND_WATCHER'
export const POPULAR_BRAND_SUCCESS = 'POPULAR_BRAND_SUCCESS'
export const POPULAR_BRAND_FAILURE = 'POPULAR_BRAND_FAILURE'

//for Popular Category
export const POPULAR_CATEGORY_WATCHER = 'POPULAR_CATEGORY_WATCHER'
export const POPULAR_CATEGORY_SUCCESS = 'POPULAR_CATEGORY_SUCCESS'
export const POPULAR_CATEGORY_FAILURE = 'POPULAR_CATEGORY_FAILURE'

//for Top Offers
export const TOP_OFFERS_WATCHER = 'TOP_OFFERS_WATCHER'
export const TOP_OFFERS_SUCCESS = 'TOP_OFFERS_SUCCESS'
export const TOP_OFFERS_FAILURE = 'TOP_OFFERS_FAILURE'

//for Nearest Merchant
export const MERCHANT_WATCHER = 'MERCHANT_WATCHER'
export const MERCHANT_SUCCESS = 'MERCHANT_SUCCESS'
export const MERCHANT_FAILURE = 'MERCHANT_FAILURE'


export default ActionTypes

