require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'HomeBottom' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  permissions_path = '../node_modules/react-native-permissions/ios'

  pod 'Permission-PhotoLibrary', :path => "#{permissions_path}/PhotoLibrary"

  pod 'react-native-geolocation', :path => '../node_modules/@react-native-community/geolocation'

  pod 'RNPermissions', :path => '../node_modules/react-native-permissions'

  pod 'RNImageCropPicker', :path => '../node_modules/react-native-image-crop-picker'

  target 'HomeBottomTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'HomeBottom-tvOS' do
  # Pods for HomeBottom-tvOS

  target 'HomeBottom-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
